--- Jupyter Notebook Hosted on IBM Cloud: https://rb.gy/hffo4e

--- TOTAL CASES VS TOTAL DEATHS ---¶
--- Query 1A ---
SELECT LOCATION, DATE, TOTAL_CASES, NEW_CASES, TOTAL_DEATHS, POPULATION
  FROM COVID_DEATH_DATA
  WHERE LOCATION LIKE 'Canada'
;
--- Query 1B: The chance of dying if you contract COVID-19 in Canada  ---
SELECT LOCATION, DATE, TOTAL_CASES, TOTAL_DEATHS, (CAST(TOTAL_DEATHS AS FLOAT)/CAST(TOTAL_CASES AS FLOAT))*100 AS DEATH_PERCENTAGE
  FROM COVID_DEATH_DATA
  WHERE LOCATION LIKE 'Canada' AND TOTAL_DEATHS IS NOT NULL
;	

--- TOTAL CASES VS POPULATION ---
--- Query 2A:The percentage of the population that contracted COVID-19 in Canada ---	
SELECT LOCATION, DATE, POPULATION, TOTAL_CASES, (CAST(TOTAL_CASES AS FLOAT)/CAST(POPULATION AS FLOAT))*100 AS CASE_PERCENTAGE
  FROM COVID_DEATH_DATA
  WHERE LOCATION = 'Canada' AND TOTAL_DEATHS IS NOT NULL AND CONTINENT IS NOT NULL
;
--- Query 2B: Countries with the highest infection rate compared to the population ---
SELECT LOCATION, POPULATION, MAX(TOTAL_CASES) AS HIGHEST_INFECTION_COUNT, MAX((CAST(TOTAL_CASES AS FLOAT)/CAST(POPULATION AS FLOAT)))*100 AS POPULATION_INFECTED_PERCENT
  FROM COVID_DEATH_DATA
  WHERE CONTINENT IS NOT NULL
  GROUP BY LOCATION, POPULATION
  ORDER BY POPULATION_INFECTED_PERCENT DESC NULLS LAST
;	
--- Query 2C: Countries with the higest death count per population ---
SELECT LOCATION, MAX(TOTAL_DEATHS) AS TOTAL_DEATH_COUNT
  FROM COVID_DEATH_DATA
  WHERE CONTINENT IS NOT NULL
  GROUP BY LOCATION, POPULATION
  ORDER BY TOTAL_DEATH_COUNT DESC NULLS LAST
;
--- Query 2D: Continent with the highest death count compared to population ---
 SELECT CONTINENT, MAX(TOTAL_DEATHS) AS HIGHEST_DEATH_COUNT, MAX((CAST(TOTAL_DEATHS AS FLOAT)/CAST(POPULATION AS FLOAT)))*100 AS MORTALITY_RATE
  FROM COVID_DEATH_DATA
  WHERE CONTINENT IS NOT NULL
  GROUP BY CONTINENT
  ORDER BY HIGHEST_DEATH_COUNT DESC LIMIT 1
;

--- GLOBAL NUMBERS ---
--- Query 3A: Mortality rate per day ---
SELECT DATE, SUM(NEW_CASES) AS TOTAL_GLOBAL_CASES, SUM(NEW_DEATHS) AS TOTAL_GLOBAL_DEATHS, SUM(CAST(NEW_DEATHS AS FLOAT))/SUM(CAST(NEW_CASES AS FLOAT))*100 AS DEATH_PERCENTAGE
  FROM COVID_DEATH_DATA
  WHERE CONTINENT IS NOT NULL
  GROUP BY DATE
  ORDER BY DATE
;
--- Query 3B: Death Percentage for the entire world ---
SELECT SUM(NEW_CASES) AS TOTAL_GLOBAL_CASES, SUM(NEW_DEATHS) AS TOTAL_GLOBAL_DEATHS, SUM(CAST(NEW_DEATHS AS FLOAT))/SUM(CAST(NEW_CASES AS FLOAT))*100 AS DEATH_PERCENTAGE
  FROM COVID_DEATH_DATA
  WHERE CONTINENT IS NOT NULL
;

--- TOTAL CASES VS VACCINATIONS ---
--- Query 4A ---
WITH
   POPVSVAC (
    CONTINENT,
    LOCATION,
    DATE,
    POPULATION,
    NEW_VACCINATIONS,
    ROLLING_PPL_VACCINATED
  )
AS 
(
  SELECT CD.CONTINENT, CD.LOCATION, CD.DATE, CD.POPULATION, CV.NEW_VACCINATIONS, SUM(CAST(CV.NEW_VACCINATIONS AS FLOAT)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION, CD.DATE) AS ROLLING_PPL_VACCINATED
  FROM COVID_DEATH_DATA CD
  FULL OUTER JOIN COVID_VACCINE_DATA AS CV ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
  WHERE CD.CONTINENT IS NOT NULL
  ORDER BY 2,3
)
  SELECT *, (ROLLING_PPL_VACCINATED/POPULATION)*100 AS PERCENT_OF_POP_VAXED
  FROM POPVSVAC
  GROUP BY CONTINENT, LOCATION, DATE, POPULATION, NEW_VACCINATIONS, ROLLING_PPL_VACCINATED
  ORDER BY 2, 3;
;
--- Query 4B: Create view of percent of population vaccinated ---
CREATE VIEW PERCENT_POP_VAXED
SELECT CD.CONTINENT, CD.LOCATION, CD.DATE, CD.POPULATION, CV.NEW_VACCINATIONS, SUM(CAST(CV.NEW_VACCINATIONS AS FLOAT)) OVER (PARTITION BY CD.LOCATION ORDER BY CD.LOCATION, CD.DATE) AS ROLLING_PPL_VACCINATED
  FROM COVID_DEATH_DATA CD
  FULL OUTER JOIN COVID_VACCINE_DATA AS CV ON CD.LOCATION = CV.LOCATION AND CD.DATE = CV.DATE
  WHERE CD.CONTINENT IS NOT NULL
;

